language: python
python:
    - 2.7
    - 3.4

env:
    - GIRDER_TEST_GROUP=python
    - GIRDER_TEST_GROUP=browser
    - GIRDER_TEST_GORUP=ansible

matrix:
    exclude:
        - python: 3.4
          env: GIRDER_TEST_GROUP=browser
        - python: 3.4
          env: GIRDER_TEST_GROUP=ansible

cache:
    directories:
        - $HOME/.cache

sudo: false

compiler:
    - gcc
before_install:
    # Show the memory state; this lets us more quickly determine when the
    # travis environment is bad
    - if [ ${GIRDER_TEST_GROUP} == 'browser' ]; then source ./devops/scripts/travis/default_before_install.sh; fi
    - if [ ${GIRDER_TEST_GROUP} == 'python' ]; then source ./devops/scripts/travis/default_before_install.sh; fi
    - if [ ${GIRDER_TEST_GROUP} == 'ansible' ]; then source ./devops/scripts/travis/ansible_before_install.sh; fi

install:
    - pip install -r requirements-dev.txt -e .[plugins] -e clients/python
    - npm install
script:
    - mkdir _build
    - cd _build
    - cmake -DPYTHON_COVERAGE:BOOL=${PY_COVG} -DPYTHON_VERSION:STRING=${TRAVIS_PYTHON_VERSION} ..
    - JASMINE_TIMEOUT=15000 ctest -VV -S ../cmake/travis_continuous.cmake || true
    - if [ -f test_failed ] ; then false ; fi
    - cd ..
    - git fetch --unshallow
deploy:
    provider: heroku
    buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
    strategy: git
    api_key:
        secure: RflKHQjdjo4dpebNUGHJrAi4cOchQPtKiA5q9W0iXJ09T2Ad/gZhJqwPN/MKzPb2JTRZzxrVBergjAeTjxcaVbNh97JnC+NBa77A5VFhCDELB2sN/zwjmxpiTtTgDtD8N2MOQcLoc7T8x0TRhk2pANQB3ztrvy+oDX+mq5SbuuU=
    app: girder-test
    on:
        repo: girder/girder
        branch: master
        condition: "$DEPLOY = true"
